### ISSUE TITLE
No more data available in "Kiosk" mode

### ISSUE THREAD

**Issue by mingwenz** [tijsverkoyen/HomeAssistant-FusionSolar#123]
Hi, 
it's been now a few days (december the 18th) since I can't retrieve or see "real time" data in Kiosk mode.
That is the day in which I updated my Home assistant which is currently running the following versions:
Core
2023.12.3
Supervisor
2023.12.0
Operating System
11.2
Frontend
20231208.2
Here below the error reported in the system logs:
First occurred: 18 dicembre 2023 alle ore 16:05:56 (1962 occurrences)
Last logged: 12:06:41

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/fusion_solar/energy_sensor.py", line 67, in native_value
    realtime_power = self.coordinator.data[self._data_name][ATTR_REALTIME_POWER]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'realTimePower'

**Comment by tijsverkoyen** [comment]
Can you check if you Kiosk url is still working?

**Comment by mingwenz** [comment]
Yepp, thank you for the quick feedback, infact , I did not know, but the Kiosk URL expires after one year, and that was what happened a few days ago (coincidently the same day I updated the system).I have requested a new URL and everything is working now.
Cheers!
