### ISSUE TITLE
Locally generated solar power missing

### ISSUE THREAD

**Issue by kecsap** [tijsverkoyen/HomeAssistant-FusionSolar#124]
I accidentally checked my syslog and I see this exception all the time:

```bash
Dec 29 04:29:35 zen-pi homeassistant[1183]: #033[31m2023-12-29 04:29:35.628 ERROR (SyncWorker_2) [custom_components.fusion_solar.fusion_solar.kiosk.kiosk_api] Retrieving the data failed with failCode: 0, data: neteco.pvms.sy
stemSetting.notExist#033[0m
Dec 29 04:29:35 zen-pi homeassistant[1183]: #033[31m2023-12-29 04:29:35.633 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Dec 29 04:29:35 zen-pi homeassistant[1183]: Traceback (most recent call last):
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
Dec 29 04:29:35 zen-pi homeassistant[1183]:     await self._async_refresh(log_failures=True, scheduled=True)
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
Dec 29 04:29:35 zen-pi homeassistant[1183]:     self.async_update_listeners()
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
Dec 29 04:29:35 zen-pi homeassistant[1183]:     update_callback()
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
Dec 29 04:29:35 zen-pi homeassistant[1183]:     self.async_write_ha_state()
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
Dec 29 04:29:35 zen-pi homeassistant[1183]:     self._async_write_ha_state()
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
Dec 29 04:29:35 zen-pi homeassistant[1183]:     state, attr = self._async_generate_attributes()
Dec 29 04:29:35 zen-pi homeassistant[1183]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
Dec 29 04:29:35 zen-pi homeassistant[1183]:     state = self._stringify_state(available)
Dec 29 04:29:35 zen-pi homeassistant[1183]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
Dec 29 04:29:35 zen-pi homeassistant[1183]:     if (state := self.state) is None:
Dec 29 04:29:35 zen-pi homeassistant[1183]:                  ^^^^^^^^^^
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
Dec 29 04:29:35 zen-pi homeassistant[1183]:     value = self.native_value
Dec 29 04:29:35 zen-pi homeassistant[1183]:             ^^^^^^^^^^^^^^^^^
Dec 29 04:29:35 zen-pi homeassistant[1183]:   File "/config/custom_components/fusion_solar/fusion_solar/energy_sensor.py", line 67, in native_value
Dec 29 04:29:35 zen-pi homeassistant[1183]:     realtime_power = self.coordinator.data[self._data_name][ATTR_REALTIME_POWER]
Dec 29 04:29:35 zen-pi homeassistant[1183]:                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
Dec 29 04:29:35 zen-pi homeassistant[1183]: KeyError: 'realTimePower'#033[0m
```

When looking into the Energy tab, the locally generated solar power is missing from the graphs since Nov 16th. Other stats are okay and retrieved.

**Comment by kecsap** [comment]
I think it was a problem on my side. During the updates, the Energy tab had wrong-old attribute set for consumed solar energy. After fixing that, it works now. I hope the error will also disappear from syslog.
