### ISSUE TITLE
Unexpected error fetching FusionSolarOpenAPIDeviceRealKpiType data: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by MrDadoo** [tijsverkoyen/HomeAssistant-FusionSolar#145]
**Describe the bug**
When querying FusionSolarOpenAPIDeviceRealKpiType  for type ID: 47, i get a "None" data response.
The code tries to iterate upon it and gets a "'NoneType' object is not iterable" exception.

** Debug information **

2024-01-30 09:39:28.895 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] FusionSolarOpenAPIDeviceRealKpiType Fetching data for type ID: 47
2024-01-30 09:39:29.254 DEBUG (SyncWorker_11) [custom_components.fusion_solar.fusion_solar.openapi.openapi_api] JSON data for https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi: {'data': None, 'failCode': 0, 'message': None, 'params': {'currentTime': 1706603969231, 'devIds': '1000000137278685', 'devTypeId': 47}, 'success': True}
2024-01-30 09:39:29.259 ERROR (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Unexpected error fetching FusionSolarOpenAPIDeviceRealKpiType data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/device_real_kpi_coordinator.py", line 65, in _async_update_data
    for response_data in response:
TypeError: 'NoneType' object is not iterable
2024-01-30 09:39:29.268 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Finished fetching FusionSolarOpenAPIDeviceRealKpiType data in 0.373 seconds (success: False)
2024-01-30 09:39:28.895 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] FusionSolarOpenAPIDeviceRealKpiType Fetching data for type ID: 47
2024-01-30 09:39:29.254 DEBUG (SyncWorker_11) [custom_components.fusion_solar.fusion_solar.openapi.openapi_api] JSON data for https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi: {'data': None, 'failCode': 0, 'message': None, 'params': {'currentTime': 1706603969231, 'devIds': '1000000137278685', 'devTypeId': 47}, 'success': True}
2024-01-30 09:39:29.259 ERROR (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Unexpected error fetching FusionSolarOpenAPIDeviceRealKpiType data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/device_real_kpi_coordinator.py", line 65, in _async_update_data
    for response_data in response:
TypeError: 'NoneType' object is not iterable

Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? Yes
* Are you using the latest version of this integration? Yes
* Have you looked into the closed issues and did not find a similar issue? Yes
* Are you using Kiosk or Northbound / OpenAPI mode?
* If you are using Kiosk mode. Have you checked that the url is still valid? See [I am using the kiosk mode, but the data is not updating](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#i-am-using-the-kiosk-mode-but-the-data-is-not-updating)
* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. See [How can I verify my Northbound API / OpenAPI credentials?](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/blob/master/README.md#how-can-i-verify-my-northbound-api--openapi-credentials)
* Have you checked the logs for any info? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by tijsverkoyen** [comment]
@MrDadoo would you be able to apply the changes from https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/146 in your local Home Assistant installation and report back if this resolves your issue.

**Comment by MrDadoo** [comment]
Does not solve it. Debug printout below.


As we actually are getting a None value in the json_data[ATTR_DATA] i don't see why we are rising an exception on that condition.

`"data":null,`

Shouldn't we ust ignore the content if its null?



```
2024-01-31 18:19:37.521 ERROR (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Unexpected error fetching FusionSolarOpenAPIDeviceRealKpiType data: Retrieving the data failed. Raw response: {"data":null,"failCode":0,"message":null,"params":{"currentTime":1706721577492,"devIds":"1000000137278685","devTypeId":47},"success":true}
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/device_real_kpi_coordinator.py", line 54, in _async_update_data
    response = await self.hass.async_add_executor_job(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 157, in get_dev_real_kpi
    response = self._do_call(url, json)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 199, in _do_call
    raise FusionSolarOpenApiError(f'Retrieving the data failed. Raw response: {response.text}')
custom_components.fusion_solar.fusion_solar.openapi.openapi_api.FusionSolarOpenApiError: Retrieving the data failed. Raw response: {"data":null,"failCode":0,"message":null,"params":{"currentTime":1706721577492,"devIds":"1000000137278685","devTypeId":47},"success":true}
2024-01-31 18:19:37.537 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Finished fetching FusionSolarOpenAPIDeviceRealKpiType data in 0.373 seconds (success: False)

```

**Comment by MrDadoo** [comment]
Might it be so that I don't have Realtime Data enabled on my openapi account?

**Comment by MrDadoo** [comment]
Fetching data for type ID: 1 seems to work. 
After that line in the log 
```

> 2024-01-31 18:54:23.456 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] FusionSolarOpenAPIDeviceRealKpiType Fetching data for type ID: 1
> 2024-01-31 18:54:24.009 INFO (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Fetching FusionSolarOpenAPIDeviceRealKpiType data recovered
> 2024-01-31 18:54:24.010 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Finished fetching FusionSolarOpenAPIDeviceRealKpiType data in 0.554 seconds (success: True)
```
my sensor values are updated.

But after "Fetching data for type ID: 47" all sensor data gets Invalid status and log shows

```
> 2024-01-31 18:55:27.164 DEBUG (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] FusionSolarOpenAPIDeviceRealKpiType Fetching data for type ID: 47
> 2024-01-31 18:55:27.495 ERROR (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Unexpected error fetching FusionSolarOpenAPIDeviceRealKpiType data: Retrieving the data failed. Raw response: {"data":null,"failCode":0,"message":null,"params":{"currentTime":1706723727464,"devIds":"1000000137278685","devTypeId":47},"success":true}
>   File "/config/custom_components/fusion_solar/device_real_kpi_coordinator.py", line 54, in _async_update_data

```

**Comment by tobyknobi** [comment]
After Huawei has updated there server. I have no data. I have no time to look into it yet to see what is happening

**Comment by danielhunt** [comment]
> After Huawei has updated there server. I have no data. I have no time to look into it yet to see what is happening

Noticing the exact same here - I'm missing data for the past 3 days (since their server updates on 30th Jan)

**Comment by danielhunt** [comment]
> > After Huawei has updated there server. I have no data. I have no time to look into it yet to see what is happening
> 
> 
> 
> Noticing the exact same here - I'm missing data for the past 3 days (since their server updates on 30th Jan)

Actually - it turns out that data has started flowing again shortly after I sent that message.

And I _think_ the reason is that I logged into FusionSolar's web app and accepted the privacy notice change that popped up...

**Comment by tobyknobi** [comment]
> > > After Huawei has updated there server. I have no data. I have no time to look into it yet to see what is happening
> > 
> > 
> > Noticing the exact same here - I'm missing data for the past 3 days (since their server updates on 30th Jan)
> 
> Actually - it turns out that data has started flowing again shortly after I sent that message.
> 
> And I _think_ the reason is that I logged into FusionSolar's web app and accepted the privacy notice change that popped up...

Unfortunately I still don't have a flow off data. Just updated the integration and ha, but still nothing. I even logged out of the app.

**Comment by danielhunt** [comment]
> 
> > And I _think_ the reason is that I logged into FusionSolar's web app and accepted the privacy notice change that popped up...
> 
> 
> 
> Unfortunately I still don't have a flow off data. Just updated the integration and ha, but still nothing. I even logged out of the app. 

And have you accepted the new privacy policy after logging into the FusionSolar web app?

**Comment by danielhunt** [comment]
Actually I'm not sure what's going on. I definitely have data but I also see this in the logs:

```
2024-02-02 21:14:45.645 ERROR (MainThread) [custom_components.fusion_solar.device_real_kpi_coordinator] Error requesting FusionSolarOpenAPIDeviceRealKpiType data: 504 Server Error: Gateway Timeout for url: https://eu5.fusionsolar.huawei.com/thirdData/getDevRealKpi
```

So there's clearly still a problem

**Comment by tobyknobi** [comment]
> > > And I _think_ the reason is that I logged into FusionSolar's web app and accepted the privacy notice change that popped up...
> > 
> > 
> > Unfortunately I still don't have a flow off data. Just updated the integration and ha, but still nothing. I even logged out of the app.
> 
> And have you accepted the new privacy policy after logging into the FusionSolar web app?

Was looking for it. That's why I logged out but didn't get it.

**Comment by MrDadoo** [comment]
I've been able to play with  POSTMAN and the API

The getDevRealKpi for ID 47 (in my setup) is the problematic one and it returns the following.

```
{
    "data": null,
    "failCode": 0,
    "message": null,
    "params": {
        "currentTime": 1706915299417,
        "devIds": "100000013XXXXXX",
        "devTypeId": 47
    },
    "success": true
}

```

I guess that the HA integration shall accept that devices have no data (or eventually I don't have access) and not make the other devices invalid.
Can that be handled?

**Comment by tobyknobi** [comment]
It looks like mine is working again. I did a recreate container in portainer (although it did this before) and now it looks like it's working again. (did not even pull a new image)

**Comment by tijsverkoyen** [comment]
`getDevRealKpi` is used to update multiple entities. So that is why "all" entities are unavailable.

I have created https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/pull/148 which seems to resolve this. As it will not update any entity if the data object is empty.
