### ISSUE TITLE
No module named 'homeassistant.core_config'

### ISSUE THREAD

**Issue by pflegair** [tijsverkoyen/HomeAssistant-FusionSolar#206]
**Describe the bug**
Directly after the update from 3.0.5 to 3.0.6 and the followin restart all entities stopped reporting.

The logs state: No module named 'homeassistant.core_config'
Logger: homeassistant.setup
Source: setup.py:334

** Debug information **
Home Assistant running in Docker
Answer the questions below before submitting a new issue.

* Are you using the latest version of Home Assistant? yes
* Are you using the latest version of this integration? yes
* Have you looked into the closed issues and did not find a similar issue. yes
* Are you using Kiosk or Northbound / OpenAPI mode? API

* If you ar using Northbound / OpenAPI mode. Check if your credentials are still valid. yes
* Have you checked the logs for any info?  yes, but not fluent in PC speak

**To Reproduce**
1. update to 3.0.6
2.  restart
3.  ???
4.  profit

**Comment by aurimas-btk** [comment]
I'm using Kiosk mode. URL is working properly. 
Error after upgrade to 3.0.6:

Logger: homeassistant.setup
Source: setup.py:334
First occurred: November 22, 2024 at 23:00:41 (1 occurrences)
Last logged: November 22, 2024 at 23:00:41

Setup failed for custom integration 'fusion_solar': Unable to import component: No module named 'homeassistant.core_config'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/fusion_solar/__init__.py", line 5, in <module>
    from homeassistant.core_config import Config
ModuleNotFoundError: No module named 'homeassistant.core_config'

**Comment by wompiefor2024** [comment]
Same isue:
Directly after the update from 3.0.5 to 3.0.6 and the followin restart all entities stopped reporting.
The logs state: No module named 'homeassistant.core_config'
Runs in Docker

**Comment by tijsverkoyen** [comment]
Which version of Home Assistant are you using?

**Comment by aurimas-btk** [comment]
10.03. Issue fixed after upgrade to 11.03

**Comment by pflegair** [comment]
> @pflegair @wompiefor2024 can you check if you are using the latest version of Home Assistant please.

same as for @aurimas-btk. Works like a charm again after updating HA core. Thanks for your amazing work @tijsverkoyen

**Comment by wompiefor2024** [comment]
> @pflegair @wompiefor2024 can you check if you are using the latest version of Home Assistant please.

I had a old version of HA. After a upgrade it worked. Thank you for the assistence and your fine work with the plugin!

**Comment by mrtnrey** [comment]
Same for me: I had to update the container image of the HA core. Now running v2024.11.3 and the Fusionsolar integration started working again. Thanks @tijsverkoyen for the great work!
