### ISSUE TITLE
OpenAPI Issue

### ISSUE THREAD

**Issue by mkosmida2** [tijsverkoyen/HomeAssistant-FusionSolar#26]
Latest version seems to cause issues when using OpenAPI

Unexpected error fetching FusionSolarOpenAPIStationYearKpi data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/fusion_solar/sensor.py", line 216, in async_update_station_year_kpi_data
    response = await hass.async_add_executor_job(api.get_kpi_station_year, station_codes)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py", line 94, in get_kpi_station_year
    return response[ATTR_DATA]
TypeError: 'NoneType' object is not subscriptable

**Comment by mkosmida2** [comment]
dunno if its related but also getting this as well

Logger: custom_components.fusion_solar.fusion_solar.openapi.openapi_api
Source: custom_components/fusion_solar/fusion_solar/openapi/openapi_api.py:130
Integration: FusionSolar (documentation, issues)
First occurred: 20:34:34 (14 occurrences)
Last logged: 20:49:34

'message'
{"data":"ACCESS_FREQUENCY_IS_TOO_HIGH","failCode":407,"params":null,"success":false}

**Comment by tijsverkoyen** [comment]
This is the same issue as in https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/25
I will try to find a solution.

**Comment by mkosmida2** [comment]
thanks

**Comment by tijsverkoyen** [comment]
The issue should be resolved as soon as you have installed [v2.2.0](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/releases/tag/v2.2.0)
