### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by catalinbordan** [tijsverkoyen/HomeAssistant-FusionSolar#60]
Hi,
I can see that I had some errors in the last night, probably because the server of Huawei was offline, or network issues.

first errror:

```
Logger: custom_components.fusion_solar.sensor
Source: helpers/update_coordinator.py:182
Integration: FusionSolar ([documentation](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar), [issues](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues))
First occurred: 04:00:58 (1 occurrences)
Last logged: 04:00:58

Error requesting FusionSolarKiosk data: HTTPSConnectionPool(host='region02eu5.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /rest/pvms/web/kiosk/v1/station-kiosk-file?kk=XXXXXXXXXX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49a3dcb7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

second error: 
```
Logger: homeassistant
Source: custom_components/fusion_solar/fusion_solar/energy_sensor.py:67
Integration: FusionSolar (documentation, issues)
First occurred: 04:10:58 (21 occurrences)
Last logged: 07:30:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 135, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 390, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 566, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 607, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 572, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fusion_solar/fusion_solar/energy_sensor.py", line 67, in state
    return float(current_value)
ValueError: could not convert string to float: 'unavailable'
```

Probably we need to avoid convert to float the state: unavailable
I'm not a programmer, but probably should be like:

 ```
               if realtime_power == '0.00':
                    _LOGGER.info(
                        f'{self.entity_id}: not producing any power, so not updating to prevent positive glitched.')
                    if current_value == 'unavailable':
                         None
                         return float(current_value)

```

**Comment by catalinbordan** [comment]
Hi,

I just let you know, it did not fix it. Your changes in the code it should be before line no 67, no?
